# Controls how many instances of RStudio Connect will be created.
# A value > 1 requires HTTP sticky sessions.
# See examples/connect/high-availability-nginx-launcher/values.yaml for an example with replicas > 1
replicas: 1

service:
  type: LoadBalancer
  port: 443
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "" # The ARN of the certificate to use
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb

# rstudio-connect.gcfg
config:
  Server:
    Address: "" # A valid https:// URL that can be verified by the aws-load-balancer-ssl-cert above
