apiVersion: v2
name: rstudio-launcher-rbac
description: RBAC definition for the RStudio Job Launcher
type: application
version: 0.2.4
appVersion: 0.2.4
icon: https://rstudio.com/wp-content/uploads/2018/10/RStudio-Logo-Flat.png
maintainers:
  - name: sol-eng
    email: docker@rstudio.com
    url: https://github.com/sol-eng
dependencies:
  - name: rstudio-library
    version: 0.1.14
    repository: file://../rstudio-library
