---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rstudio-workbench.fullname" . }}-session
  namespace: {{ $.Release.Namespace }}
data:
{{ include "rstudio-library.config.ini" .Values.config.session | indent 2 }}
---
