apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rstudio-workbench.fullname" . }}-start-rsw
  namespace: {{ $.Release.Namespace }}
data:
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rstudio-workbench.fullname" . }}-start-launcher
  namespace: {{ $.Release.Namespace }}
data:

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rstudio-workbench.fullname" . }}-start-sssd
  namespace: {{ $.Release.Namespace }}
data:

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rstudio-workbench.fullname" . }}-start-custom
  namespace: {{ $.Release.Namespace }}
data:
