{{- if .Values.rbac.create }}
{{ $namespace := $.Release.Namespace }}
{{ $targetNamespace := default $.Release.Namespace .Values.launcher.namespace }}
{{ $serviceAccountName := default (include "rstudio-workbench.fullname" .) .Values.rbac.serviceAccount.name }}
{{ $serviceAccountCreate := .Values.rbac.create }}
{{ $serviceAccountAnnotations := .Values.serviceAccountAnnotations }}
{{ $rbacValues1 := dict "namespace" $namespace "serviceAccountName" $serviceAccountName "targetNamespace" $targetNamespace }}
{{ $rbacValues2 := dict "serviceAccountCreate" $.Values.rbac.create "serviceAccountAnnotations" $serviceAccountAnnotations }}
{{ $rbacValues := merge $rbacValues1 $rbacValues2 }}
{{ include "rstudio-library.rbac" $rbacValues }}
{{- end }}
