---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rstudio-workbench.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "rstudio-workbench.labels" . | nindent 4 }}
  annotations:
{{ include "rstudio-workbench.annotations" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "rstudio-workbench.selectorLabels" . | nindent 4 }}
  ports:
  - protocol: TCP
    port: 80
    {{- if .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
    targetPort: 8787
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rstudio-workbench.fullname" . }}-launcher
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "rstudio-workbench.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    {{- include "rstudio-workbench.selectorLabels" . | nindent 4 }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5559
---
