apiVersion: v2
name: rstudio-library
description: Helm library helpers for use by Official RStudio charts
type: library
version: 0.1.14
appVersion: 0.1.14
icon: https://rstudio.com/wp-content/uploads/2018/10/RStudio-Logo-Flat.png
home: https://www.rstudio.com
maintainers:
  - name: sol-eng
    email: docker@rstudio.com
    url: https://github.com/rstudio/helm
