---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rstudio-pm.fullname" . }}-config
  namespace: {{ $.Release.Namespace }}
data:
  rstudio-pm.gcfg: |
{{ include "rstudio-pm.config" . | indent 4 }}
