{{- if .Values.rstudioPMKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rstudio-pm.fullname" . }}-rstudio-pm-key
  namespace: {{ $.Release.Namespace }}
type: Opaque
stringData:
  rstudio-pm.key: {{ .Values.rstudioPMKey }}
{{- end }}
