{{- if .Values.awsAccessKeyId }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rstudio-pm.fullname" . }}-aws-creds
  namespace: {{ $.Release.Namespace }}
type: Opaque
stringData:
  credentials: |
    [default] 
    aws_access_key_id={{ .Values.awsAccessKeyId }}
    aws_secret_access_key={{ .Values.awsSecretAccessKey }}
{{- end }}
