{{- if .Values.launcher.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rstudio-connect.fullname" . }}-prestart
  namespace: {{ $.Release.Namespace }}
data:
  prestart.bash: |
    {{- .Files.Get "prestart.bash" | nindent 4 }}
{{- end }}
