name: Rebuild index.yaml manually
on:
  workflow_dispatch:

jobs:
  document:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.6.3

      - name: Set up chart-releaser
        uses: helm/chart-releaser-action@v1.2.0

      - name: Rebuild index.yaml
        run: |
          echo "Hello Jon"
