name: Compute example rbac files

on:
  push:
    paths:
      - 'charts/rstudio-launcher-rbac/**'
      - '.github/workflows/chart-example-rbac.yaml'

jobs:
  document:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.6.3

      - name: Compute and update dependent files
        run: |
          set -xe
          cd ./charts/rstudio-launcher-rbac && helm dependency build && cd -
          helm template -n rstudio rstudio-launcher-rbac ./charts/rstudio-launcher-rbac --set removeNamespaceReferences=true > examples/rbac/rstudio-launcher-rbac.yaml
          CHART_VERSION=$(helm show chart ./charts/rstudio-launcher-rbac | grep '^version' | cut -d ' ' -f 2)
          cp examples/rbac/rstudio-launcher-rbac.yaml examples/rbac/rstudio-launcher-rbac-${CHART_VERSION}.yaml

      - name: Commit results
        run: |
          set -xeo pipefail
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add examples/rbac/rstudio-launcher-rbac*.yaml || echo "No files to add"
          git commit examples/rbac/rstudio-launcher-rbac*.yaml -m 'Update rbac yaml' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
